(use-package w3m
  :ensure t
  :init (setq w3m-mode-map (make-sparse-keymap))
;  :config (progn (require 'w3m-haddock)
;                 (add-hook 'w3m-display-hook 'w3m-haddock-display))
;  :bind (("C-c C-d" . haskell-w3m-open-haddock)
;         ("RET" . w3m-view-this-url)
;         ("q" . bury-buffer)
;         ("<mouse-1>" . w3m-maybe-url)
;         ("<f5>" . w3m-reload-this-page)
;         ("C-c C-d" . haskell-w3m-open-haddock)
;         ("M-<left>" . w3m-view-previous-page)
;         ("M-<right>" . w3m-view-next-page)
;         ("M-." . w3m-haddock-find-tag)))
)
(defun w3m-maybe-url ()
  (interactive)
  (if (or (equal '(w3m-anchor) (get-text-property (point) 'face))
          (equal '(w3m-arrived-anchor) (get-text-property (point) 'face)))
      (w3m-view-this-url)))
